### ISSUE TITLE
Links with line breaks break external-links filter and potentially eat up HTML

### ISSUE THREAD

**Issue by archon810** [semiologic/sem-external-links#2]
Hi,

I hope this is the right place to report this, especially since there's a PR coming.

I have notices enabled, which all go to Sentry, and I noticed numerous cases of sem-external-links triggering a notice in update_attribute():

`Undefined offset: 1`

```
preg_match('/(<a.*>)/iU', $html, $match);
$link_str = $match[1];
```

Upon digging further, I discovered that some nasty spammers leave links with line breaks in them, like so:
```
<a href="http://www.spamsite.com/tag/ipl-all-match-

schedule">IPL 2017 All Match schedule</a></p>
```

Because the regex isn't set up to look for multiple lines, it gets confused and the function returns right away, resulting in no no-follow and external added to the link.

What's worse, and I can't quite figure out why, but a large chunk of comments preceding the nasty link comment just disappears, and seemingly randomly too, thus breaking HTML (literally, mid-sentence). It has something to do with output buffering in the WP code, and some of the preceding buffer disappears.

However, adding "/s" to the regex seems to not only fix the no-follow/externals issue, but also restores the missing chunk.

I'm going to PR this in a second.

**Comment by archon810** [comment]
Created a topic here just in case https://wordpress.org/support/topic/links-with-line-breaks-break-external-links-filter-and-potentially-eat-up-html/.

**Comment by archon810** [comment]
Side question: I compared 6.7 on github and 6.7 in WP's repo, and WP still lists anchor-utils.php (which is unused) and sem-follow_comment.php is present there and not on git.

There's also a fix `if(!empty($domain)){` in git but not in WP's version.

Why the discrepancies?

**Comment by mkoepke** [comment]
I'll be releasing a 6.8 release soon with these PRs.  Thanks for reporting the issue along with the fix.
